/**
 * MarketPunk - Configuração de Recursos
 */

import { Resource, Recipe, Vector2D } from '../types';

// ============================================================================
// RECURSOS (TIER 1-5)
// ============================================================================

export function getResources(): Resource[] {
  return [
    // TIER 1: Recursos Brutos
    { id: 'wood', name: 'Wood', tier: 1, category: 'raw', basePrice: 1, stackSize: 100, isRaw: true },
    { id: 'stone', name: 'Stone', tier: 1, category: 'raw', basePrice: 1, stackSize: 100, isRaw: true },
    { id: 'iron_ore', name: 'Iron Ore', tier: 1, category: 'raw', basePrice: 5, stackSize: 50, isRaw: true },
    { id: 'coal', name: 'Coal', tier: 1, category: 'raw', basePrice: 2, stackSize: 50, isRaw: true },
    { id: 'sand', name: 'Sand', tier: 1, category: 'raw', basePrice: 1, stackSize: 100, isRaw: true },
    { id: 'water', name: 'Water', tier: 1, category: 'raw', basePrice: 0.5, stackSize: 100, isRaw: true },
    { id: 'copper_ore', name: 'Copper Ore', tier: 1, category: 'raw', basePrice: 8, stackSize: 30, isRaw: true },
    { id: 'limestone', name: 'Limestone', tier: 1, category: 'raw', basePrice: 3, stackSize: 50, isRaw: true },
    { id: 'crude_oil', name: 'Crude Oil', tier: 1, category: 'raw', basePrice: 10, stackSize: 20, isRaw: true },
    { id: 'sulfur', name: 'Sulfur', tier: 1, category: 'raw', basePrice: 15, stackSize: 20, isRaw: true },
    { id: 'clay', name: 'Clay', tier: 1, category: 'raw', basePrice: 2, stackSize: 50, isRaw: true },
    { id: 'lead', name: 'Lead', tier: 1, category: 'raw', basePrice: 12, stackSize: 30, isRaw: true },
    { id: 'gold', name: 'Gold', tier: 1, category: 'raw', basePrice: 100, stackSize: 10, isRaw: true },
    { id: 'uranium', name: 'Uranium', tier: 1, category: 'raw', basePrice: 50, stackSize: 5, isRaw: true },
    { id: 'thorium', name: 'Thorium', tier: 1, category: 'raw', basePrice: 100, stackSize: 5, isRaw: true },

    // TIER 2: Processamento Básico
    { id: 'lumber', name: 'Lumber', tier: 2, category: 'processed', basePrice: 4, stackSize: 50, isRaw: false },
    { id: 'stone_block', name: 'Stone Block', tier: 2, category: 'processed', basePrice: 2, stackSize: 50, isRaw: false },
    { id: 'iron_ingot', name: 'Iron Ingot', tier: 2, category: 'processed', basePrice: 12, stackSize: 30, isRaw: false },
    { id: 'copper_ingot', name: 'Copper Ingot', tier: 2, category: 'processed', basePrice: 15, stackSize: 30, isRaw: false },
    { id: 'coal_brick', name: 'Coal Brick', tier: 2, category: 'processed', basePrice: 3, stackSize: 50, isRaw: false },
    { id: 'glass_sheet', name: 'Glass Sheet', tier: 2, category: 'processed', basePrice: 8, stackSize: 20, isRaw: false },
    { id: 'purified_water', name: 'Purified Water', tier: 2, category: 'processed', basePrice: 1, stackSize: 50, isRaw: false },
    { id: 'quicklime', name: 'Quicklime', tier: 2, category: 'processed', basePrice: 5, stackSize: 30, isRaw: false },
    { id: 'charcoal', name: 'Charcoal', tier: 2, category: 'processed', basePrice: 3, stackSize: 50, isRaw: false },
    { id: 'crude_oil_extract', name: 'Crude Oil Extract', tier: 2, category: 'processed', basePrice: 12, stackSize: 20, isRaw: false },

    // TIER 3: Materiais Industriais
    { id: 'steel', name: 'Steel', tier: 3, category: 'material', basePrice: 20, stackSize: 30, isRaw: false },
    { id: 'steel_sheet', name: 'Steel Sheet', tier: 3, category: 'material', basePrice: 25, stackSize: 20, isRaw: false },
    { id: 'steel_pipe', name: 'Steel Pipe', tier: 3, category: 'material', basePrice: 15, stackSize: 30, isRaw: false },
    { id: 'copper_wire', name: 'Copper Wire', tier: 3, category: 'material', basePrice: 3, stackSize: 100, isRaw: false },
    { id: 'plastic', name: 'Plastic', tier: 3, category: 'material', basePrice: 15, stackSize: 30, isRaw: false },
    { id: 'rubber', name: 'Rubber', tier: 3, category: 'material', basePrice: 10, stackSize: 30, isRaw: false },
    { id: 'cement', name: 'Cement', tier: 3, category: 'material', basePrice: 8, stackSize: 30, isRaw: false },
    { id: 'brick', name: 'Brick', tier: 3, category: 'material', basePrice: 3, stackSize: 50, isRaw: false },
    { id: 'aluminum_ingot', name: 'Aluminum Ingot', tier: 3, category: 'material', basePrice: 30, stackSize: 20, isRaw: false },
    { id: 'chemical_resin', name: 'Chemical Resin', tier: 3, category: 'material', basePrice: 12, stackSize: 30, isRaw: false },
    { id: 'fuel_oil', name: 'Fuel Oil', tier: 3, category: 'material', basePrice: 15, stackSize: 20, isRaw: false },
    { id: 'sulfuric_acid', name: 'Sulfuric Acid', tier: 3, category: 'material', basePrice: 20, stackSize: 20, isRaw: false },
    { id: 'lead_ingot', name: 'Lead Ingot', tier: 3, category: 'material', basePrice: 20, stackSize: 20, isRaw: false },
    { id: 'graphite', name: 'Graphite', tier: 3, category: 'material', basePrice: 25, stackSize: 20, isRaw: false },

    // TIER 4: Componentes Intermediários
    { id: 'gear', name: 'Gear', tier: 4, category: 'component', basePrice: 5, stackSize: 100, isRaw: false },
    { id: 'bearing', name: 'Bearing', tier: 4, category: 'component', basePrice: 8, stackSize: 50, isRaw: false },
    { id: 'electric_motor', name: 'Electric Motor', tier: 4, category: 'component', basePrice: 50, stackSize: 10, isRaw: false },
    { id: 'magnetic_steel', name: 'Magnetic Steel', tier: 4, category: 'component', basePrice: 30, stackSize: 20, isRaw: false },
    { id: 'integrated_circuit', name: 'Integrated Circuit', tier: 4, category: 'component', basePrice: 15, stackSize: 50, isRaw: false },
    { id: 'advanced_ic', name: 'Advanced IC', tier: 4, category: 'component', basePrice: 40, stackSize: 20, isRaw: false },
    { id: 'pcb', name: 'PCB', tier: 4, category: 'component', basePrice: 10, stackSize: 30, isRaw: false },
    { id: 'pipe_assembly', name: 'Pipe Assembly', tier: 4, category: 'component', basePrice: 20, stackSize: 20, isRaw: false },
    { id: 'gearbox', name: 'Gearbox', tier: 4, category: 'component', basePrice: 40, stackSize: 10, isRaw: false },
    { id: 'control_unit', name: 'Control Unit', tier: 4, category: 'component', basePrice: 60, stackSize: 10, isRaw: false },
    { id: 'battery', name: 'Battery', tier: 4, category: 'component', basePrice: 50, stackSize: 20, isRaw: false },
    { id: 'solar_cell', name: 'Solar Cell', tier: 4, category: 'component', basePrice: 35, stackSize: 20, isRaw: false },
    { id: 'heat_exchanger', name: 'Heat Exchanger', tier: 4, category: 'component', basePrice: 45, stackSize: 10, isRaw: false },

    // TIER 4B: Manutenção
    { id: 'lubricant', name: 'Lubricant', tier: 4, category: 'maintenance', basePrice: 8, stackSize: 50, isRaw: false },
    { id: 'coolant', name: 'Coolant', tier: 4, category: 'maintenance', basePrice: 10, stackSize: 30, isRaw: false },
    { id: 'spare_parts', name: 'Spare Parts', tier: 4, category: 'maintenance', basePrice: 15, stackSize: 30, isRaw: false },
    { id: 'gold_filament', name: 'Gold Filament', tier: 4, category: 'component', basePrice: 50, stackSize: 20, isRaw: false },

    // TIER 5: Produtos Finais
    { id: 'basic_factory_machine', name: 'Basic Factory Machine', tier: 5, category: 'product', basePrice: 500, stackSize: 5, isRaw: false },
    { id: 'advanced_factory_machine', name: 'Advanced Factory Machine', tier: 5, category: 'product', basePrice: 1000, stackSize: 3, isRaw: false },
    { id: 'basic_electronics', name: 'Basic Electronics', tier: 5, category: 'product', basePrice: 100, stackSize: 10, isRaw: false },
    { id: 'advanced_electronics', name: 'Advanced Electronics', tier: 5, category: 'product', basePrice: 250, stackSize: 5, isRaw: false },
    { id: 'food_ration', name: 'Food Ration', tier: 5, category: 'product', basePrice: 2, stackSize: 100, isRaw: false },
    { id: 'medical_supply', name: 'Medical Supply', tier: 5, category: 'product', basePrice: 15, stackSize: 30, isRaw: false },
    { id: 'comfort_item', name: 'Comfort Item', tier: 5, category: 'product', basePrice: 10, stackSize: 30, isRaw: false },
    { id: 'building_block', name: 'Building Block', tier: 5, category: 'product', basePrice: 8, stackSize: 50, isRaw: false },
    { id: 'steel_frame', name: 'Steel Frame', tier: 5, category: 'product', basePrice: 80, stackSize: 10, isRaw: false },
    { id: 'reinforced_glass', name: 'Reinforced Glass', tier: 5, category: 'product', basePrice: 25, stackSize: 20, isRaw: false },
    { id: 'basic_fuel_rod', name: 'Basic Fuel Rod', tier: 5, category: 'product', basePrice: 200, stackSize: 5, isRaw: false },
    { id: 'advanced_fuel_rod', name: 'Advanced Fuel Rod', tier: 5, category: 'product', basePrice: 500, stackSize: 3, isRaw: false },
    { id: 'basic_vehicle', name: 'Basic Vehicle', tier: 5, category: 'product', basePrice: 800, stackSize: 3, isRaw: false },
    { id: 'transport_truck', name: 'Transport Truck', tier: 5, category: 'product', basePrice: 1500, stackSize: 2, isRaw: false },
    { id: 'basic_tool_set', name: 'Basic Tool Set', tier: 5, category: 'product', basePrice: 30, stackSize: 20, isRaw: false },
    { id: 'advanced_tool_set', name: 'Advanced Tool Set', tier: 5, category: 'product', basePrice: 80, stackSize: 10, isRaw: false },
    { id: 'coal_power_plant', name: 'Coal Power Plant', tier: 5, category: 'energy', basePrice: 200, stackSize: 3, isRaw: false },
    { id: 'diesel_generator', name: 'Diesel Generator', tier: 5, category: 'energy', basePrice: 500, stackSize: 2, isRaw: false },
    { id: 'solar_power_array', name: 'Solar Power Array', tier: 5, category: 'energy', basePrice: 1000, stackSize: 2, isRaw: false },
    { id: 'wind_turbine', name: 'Wind Turbine', tier: 5, category: 'energy', basePrice: 300, stackSize: 2, isRaw: false },
    { id: 'nuclear_reactor', name: 'Nuclear Reactor', tier: 5, category: 'energy', basePrice: 5000, stackSize: 1, isRaw: false },
    { id: 'basic_automation', name: 'Basic Automation', tier: 5, category: 'product', basePrice: 150, stackSize: 5, isRaw: false },
    { id: 'advanced_automation', name: 'Advanced Automation', tier: 5, category: 'product', basePrice: 400, stackSize: 3, isRaw: false },
    { id: 'shipping_crate', name: 'Shipping Crate', tier: 5, category: 'product', basePrice: 5, stackSize: 50, isRaw: false },
    { id: 'pallet', name: 'Pallet', tier: 5, category: 'product', basePrice: 10, stackSize: 20, isRaw: false },
  ];
}

// ============================================================================
// RECEITAS DE PRODUÇÃO
// ============================================================================

export function getRecipes(): Recipe[] {
  return [
    // TIER 2: Processamento Básico
    {
      id: 'lumber',
      name: 'Lumber',
      inputs: new Map([['wood', 3]]),
      outputs: new Map([['lumber', 1]]),
      byproducts: new Map([['sawdust', 1]]),
      timeSeconds: 3,
      complexity: 2,
      tier: 2,
      energyCost: 50,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'stone_block',
      name: 'Stone Block',
      inputs: new Map([['stone', 2]]),
      outputs: new Map([['stone_block', 1]]),
      byproducts: new Map(),
      timeSeconds: 4,
      complexity: 2,
      tier: 2,
      energyCost: 0,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'iron_ingot',
      name: 'Iron Ingot',
      inputs: new Map([['iron_ore', 2], ['coal', 1]]),
      outputs: new Map([['iron_ingot', 1]]),
      byproducts: new Map([['slag', 1]]),
      timeSeconds: 8,
      complexity: 3,
      tier: 2,
      energyCost: 100,
      heatGenerated: 20,
      category: 'refining',
    },
    {
      id: 'copper_ingot',
      name: 'Copper Ingot',
      inputs: new Map([['copper_ore', 2], ['coal', 1]]),
      outputs: new Map([['copper_ingot', 1]]),
      byproducts: new Map([['slag', 1]]),
      timeSeconds: 8,
      complexity: 3,
      tier: 2,
      energyCost: 100,
      heatGenerated: 20,
      category: 'refining',
    },
    {
      id: 'coal_brick',
      name: 'Coal Brick',
      inputs: new Map([['coal', 2]]),
      outputs: new Map([['coal_brick', 1]]),
      byproducts: new Map(),
      timeSeconds: 3,
      complexity: 2,
      tier: 2,
      energyCost: 0,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'glass_sheet',
      name: 'Glass Sheet',
      inputs: new Map([['sand', 3], ['coal_brick', 2]]),
      outputs: new Map([['glass_sheet', 1]]),
      byproducts: new Map(),
      timeSeconds: 12,
      complexity: 4,
      tier: 2,
      energyCost: 150,
      heatGenerated: 50,
      category: 'refining',
    },
    {
      id: 'purified_water',
      name: 'Purified Water',
      inputs: new Map([['water', 5], ['sand', 1]]),
      outputs: new Map([['purified_water', 2]]),
      byproducts: new Map(),
      timeSeconds: 5,
      complexity: 2,
      tier: 2,
      energyCost: 10,
      heatGenerated: 0,
      category: 'refining',
    },
    {
      id: 'quicklime',
      name: 'Quicklime',
      inputs: new Map([['limestone', 3]]),
      outputs: new Map([['quicklime', 2]]),
      byproducts: new Map(),
      timeSeconds: 10,
      complexity: 3,
      tier: 2,
      energyCost: 80,
      heatGenerated: 10,
      category: 'refining',
    },
    {
      id: 'charcoal',
      name: 'Charcoal',
      inputs: new Map([['wood', 3]]),
      outputs: new Map([['charcoal', 1]]),
      byproducts: new Map([['wood_tar', 1]]),
      timeSeconds: 6,
      complexity: 2,
      tier: 2,
      energyCost: 0,
      heatGenerated: 0,
      category: 'refining',
    },
    {
      id: 'crude_oil_extract',
      name: 'Crude Oil Extract',
      inputs: new Map([['crude_oil', 1]]),
      outputs: new Map([['crude_oil_extract', 1]]),
      byproducts: new Map(),
      timeSeconds: 4,
      complexity: 3,
      tier: 2,
      energyCost: 30,
      heatGenerated: 0,
      category: 'refining',
    },

    // TIER 3: Materiais Industriais
    {
      id: 'steel_basic',
      name: 'Basic Steel',
      inputs: new Map([['iron_ingot', 2], ['coal_brick', 1]]),
      outputs: new Map([['steel', 1]]),
      byproducts: new Map(),
      timeSeconds: 15,
      complexity: 4,
      tier: 3,
      energyCost: 200,
      heatGenerated: 100,
      category: 'refining',
    },
    {
      id: 'steel_high_carbon',
      name: 'High-Carbon Steel',
      inputs: new Map([['iron_ingot', 2], ['coal_brick', 2], ['copper_ingot', 1]]),
      outputs: new Map([['steel', 1]]), // seria 'steel_high_carbon' mas usamos o mesmo id
      byproducts: new Map(),
      timeSeconds: 20,
      complexity: 5,
      tier: 3,
      energyCost: 250,
      heatGenerated: 100,
      category: 'refining',
    },
    {
      id: 'steel_sheet',
      name: 'Steel Sheet',
      inputs: new Map([['steel', 2]]),
      outputs: new Map([['steel_sheet', 1]]),
      byproducts: new Map(),
      timeSeconds: 8,
      complexity: 4,
      tier: 3,
      energyCost: 80,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'steel_pipe',
      name: 'Steel Pipe',
      inputs: new Map([['steel', 2]]),
      outputs: new Map([['steel_pipe', 2]]),
      byproducts: new Map(),
      timeSeconds: 10,
      complexity: 4,
      tier: 3,
      energyCost: 80,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'copper_wire',
      name: 'Copper Wire',
      inputs: new Map([['copper_ingot', 1]]),
      outputs: new Map([['copper_wire', 3]]),
      byproducts: new Map(),
      timeSeconds: 6,
      complexity: 3,
      tier: 3,
      energyCost: 30,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'plastic_oil',
      name: 'Plastic (Oil)',
      inputs: new Map([['crude_oil_extract', 3]]),
      outputs: new Map([['plastic', 2]]),
      byproducts: new Map([['fuel_oil', 1], ['gas', 1]]),
      timeSeconds: 18,
      complexity: 5,
      tier: 3,
      energyCost: 150,
      heatGenerated: 30,
      category: 'refining',
    },
    {
      id: 'plastic_biomass',
      name: 'Plastic (Biomass)',
      inputs: new Map([['wood', 5], ['coal_brick', 2]]),
      outputs: new Map([['plastic', 1]]),
      byproducts: new Map(),
      timeSeconds: 25,
      complexity: 5,
      tier: 3,
      energyCost: 180,
      heatGenerated: 20,
      category: 'refining',
    },
    {
      id: 'rubber',
      name: 'Rubber',
      inputs: new Map([['plastic', 3]]),
      outputs: new Map([['rubber', 2]]),
      byproducts: new Map(),
      timeSeconds: 8,
      complexity: 4,
      tier: 3,
      energyCost: 50,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'cement',
      name: 'Cement',
      inputs: new Map([['quicklime', 2], ['sand', 2], ['slag', 1]]),
      outputs: new Map([['cement', 3]]),
      byproducts: new Map(),
      timeSeconds: 14,
      complexity: 4,
      tier: 3,
      energyCost: 100,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'brick',
      name: 'Brick',
      inputs: new Map([['clay', 3], ['quicklime', 1]]),
      outputs: new Map([['brick', 4]]),
      byproducts: new Map(),
      timeSeconds: 10,
      complexity: 4,
      tier: 3,
      energyCost: 80,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'aluminum_ingot',
      name: 'Aluminum Ingot',
      inputs: new Map([['limestone', 3], ['coal_brick', 2], ['copper_wire', 1]]),
      outputs: new Map([['aluminum_ingot', 1]]),
      byproducts: new Map(),
      timeSeconds: 22,
      complexity: 5,
      tier: 3,
      energyCost: 300,
      heatGenerated: 200,
      category: 'refining',
    },
    {
      id: 'chemical_resin',
      name: 'Chemical Resin',
      inputs: new Map([['coal', 2], ['water', 1]]),
      outputs: new Map([['chemical_resin', 1]]),
      byproducts: new Map(),
      timeSeconds: 12,
      complexity: 4,
      tier: 3,
      energyCost: 80,
      heatGenerated: 0,
      category: 'refining',
    },
    {
      id: 'fuel_oil',
      name: 'Fuel Oil',
      inputs: new Map([['crude_oil_extract', 2]]),
      outputs: new Map([['fuel_oil', 1]]),
      byproducts: new Map([['gas', 1]]),
      timeSeconds: 10,
      complexity: 4,
      tier: 3,
      energyCost: 100,
      heatGenerated: 0,
      category: 'refining',
    },
    {
      id: 'sulfuric_acid',
      name: 'Sulfuric Acid',
      inputs: new Map([['sulfur', 2], ['quicklime', 1]]),
      outputs: new Map([['sulfuric_acid', 2]]),
      byproducts: new Map(),
      timeSeconds: 16,
      complexity: 5,
      tier: 3,
      energyCost: 120,
      heatGenerated: 0,
      category: 'refining',
    },
    {
      id: 'lead_ingot',
      name: 'Lead Ingot',
      inputs: new Map([['lead', 2], ['coal_brick', 1]]),
      outputs: new Map([['lead_ingot', 1]]),
      byproducts: new Map(),
      timeSeconds: 10,
      complexity: 4,
      tier: 3,
      energyCost: 80,
      heatGenerated: 10,
      category: 'refining',
    },
    {
      id: 'graphite',
      name: 'Graphite',
      inputs: new Map([['coal', 2], ['coal_brick', 1], ['lead_ingot', 1]]),
      outputs: new Map([['graphite', 1]]),
      byproducts: new Map(),
      timeSeconds: 15,
      complexity: 5,
      tier: 3,
      energyCost: 100,
      heatGenerated: 0,
      category: 'refining',
    },

    // TIER 4: Componentes Intermediários
    {
      id: 'gear',
      name: 'Gear',
      inputs: new Map([['steel', 1]]),
      outputs: new Map([['gear', 3]]),
      byproducts: new Map([['metal_scrap', 1]]),
      timeSeconds: 6,
      complexity: 4,
      tier: 4,
      energyCost: 50,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'bearing',
      name: 'Bearing',
      inputs: new Map([['steel', 2], ['copper_wire', 1]]),
      outputs: new Map([['bearing', 2]]),
      byproducts: new Map(),
      timeSeconds: 10,
      complexity: 5,
      tier: 4,
      energyCost: 80,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'electric_motor',
      name: 'Electric Motor',
      inputs: new Map([['steel_sheet', 2], ['copper_wire', 3], ['magnetic_steel', 1]]),
      outputs: new Map([['electric_motor', 1]]),
      byproducts: new Map(),
      timeSeconds: 18,
      complexity: 6,
      tier: 4,
      energyCost: 200,
      heatGenerated: 0,
      category: 'manufacturing',
    },
    {
      id: 'magnetic_steel',
      name: 'Magnetic Steel',
      inputs: new Map([['steel', 2], ['iron_ingot', 1]]),
      outputs: new Map([['magnetic_steel', 1]]),
      byproducts: new Map(),
      timeSeconds: 14,
      complexity: 5,
      tier: 4,
      energyCost: 120,
      heatGenerated: 0,
      category: 'refining',
    },
    {
      id: 'integrated_circuit',
      name: 'Integrated Circuit',
      inputs: new Map([['copper_wire', 2], ['plastic', 1], ['chemical_resin', 1]]),
      outputs: new Map([['integrated_circuit', 1]]),
      byproducts: new Map(),
      timeSeconds: 20,
      complexity: 6,
      tier: 4,
      energyCost: 150,
      heatGenerated: 0,
      category: 'manufacturing',
    },
    {
      id: 'advanced_ic',
      name: 'Advanced IC',
      inputs: new Map([['integrated_circuit', 1], ['gold_filament', 1], ['aluminum_ingot', 1]]),
      outputs: new Map([['advanced_ic', 1]]),
      byproducts: new Map(),
      timeSeconds: 30,
      complexity: 7,
      tier: 4,
      energyCost: 250,
      heatGenerated: 0,
      category: 'manufacturing',
    },
    {
      id: 'pcb',
      name: 'PCB',
      inputs: new Map([['plastic', 2], ['copper_wire', 3], ['chemical_resin', 1]]),
      outputs: new Map([['pcb', 1]]),
      byproducts: new Map(),
      timeSeconds: 15,
      complexity: 5,
      tier: 4,
      energyCost: 100,
      heatGenerated: 0,
      category: 'manufacturing',
    },
    {
      id: 'pipe_assembly',
      name: 'Pipe Assembly',
      inputs: new Map([['steel_pipe', 4], ['rubber', 2], ['steel_sheet', 1]]),
      outputs: new Map([['pipe_assembly', 1]]),
      byproducts: new Map(),
      timeSeconds: 12,
      complexity: 5,
      tier: 4,
      energyCost: 80,
      heatGenerated: 0,
      category: 'assembly',
    },
    {
      id: 'gearbox',
      name: 'Gearbox',
      inputs: new Map([['gear', 4], ['bearing', 2], ['steel_sheet', 1]]),
      outputs: new Map([['gearbox', 1]]),
      byproducts: new Map(),
      timeSeconds: 16,
      complexity: 6,
      tier: 4,
      energyCost: 150,
      heatGenerated: 0,
      category: 'assembly',
    },
    {
      id: 'control_unit',
      name: 'Control Unit',
      inputs: new Map([['integrated_circuit', 2], ['pcb', 1], ['copper_wire', 2]]),
      outputs: new Map([['control_unit', 1]]),
      byproducts: new Map(),
      timeSeconds: 22,
      complexity: 6,
      tier: 4,
      energyCost: 200,
      heatGenerated: 0,
      category: 'manufacturing',
    },
    {
      id: 'battery',
      name: 'Battery',
      inputs: new Map([['lead_ingot', 2], ['sulfuric_acid', 1], ['plastic', 1]]),
      outputs: new Map([['battery', 1]]),
      byproducts: new Map(),
      timeSeconds: 14,
      complexity: 5,
      tier: 4,
      energyCost: 100,
      heatGenerated: 0,
      category: 'manufacturing',
    },
    {
      id: 'solar_cell',
      name: 'Solar Cell',
      inputs: new Map([['glass_sheet', 2], ['copper_wire', 1], ['aluminum_ingot', 1]]),
      outputs: new Map([['solar_cell', 1]]),
      byproducts: new Map(),
      timeSeconds: 25,
      complexity: 7,
      tier: 4,
      energyCost: 180,
      heatGenerated: 0,
      category: 'manufacturing',
    },
    {
      id: 'heat_exchanger',
      name: 'Heat Exchanger',
      inputs: new Map([['steel_pipe', 2], ['steel_sheet', 1], ['copper_wire', 1]]),
      outputs: new Map([['heat_exchanger', 1]]),
      byproducts: new Map(),
      timeSeconds: 18,
      complexity: 6,
      tier: 4,
      energyCost: 150,
      heatGenerated: 0,
      category: 'assembly',
    },

    // TIER 4B: Manutenção
    {
      id: 'lubricant',
      name: 'Lubricant',
      inputs: new Map([['rubber', 1], ['plastic', 1]]),
      outputs: new Map([['lubricant', 2]]),
      byproducts: new Map(),
      timeSeconds: 8,
      complexity: 4,
      tier: 4,
      energyCost: 30,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'coolant',
      name: 'Coolant',
      inputs: new Map([['purified_water', 2], ['chemical_resin', 1]]),
      outputs: new Map([['coolant', 2]]),
      byproducts: new Map(),
      timeSeconds: 12,
      complexity: 5,
      tier: 4,
      energyCost: 50,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'spare_parts',
      name: 'Spare Parts',
      inputs: new Map([['gear', 2], ['bearing', 1], ['steel_sheet', 1]]),
      outputs: new Map([['spare_parts', 3]]),
      byproducts: new Map(),
      timeSeconds: 15,
      complexity: 5,
      tier: 4,
      energyCost: 80,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'gold_filament',
      name: 'Gold Filament',
      inputs: new Map([['gold', 1], ['chemical_resin', 1]]),
      outputs: new Map([['gold_filament', 2]]),
      byproducts: new Map(),
      timeSeconds: 20,
      complexity: 6,
      tier: 4,
      energyCost: 100,
      heatGenerated: 0,
      category: 'crafting',
    },

    // TIER 5: Produtos Finais
    {
      id: 'basic_factory_machine',
      name: 'Basic Factory Machine',
      inputs: new Map([['steel_sheet', 3], ['gearbox', 2], ['electric_motor', 1]]),
      outputs: new Map([['basic_factory_machine', 1]]),
      byproducts: new Map(),
      timeSeconds: 45,
      complexity: 8,
      tier: 5,
      energyCost: 500,
      heatGenerated: 0,
      category: 'manufacturing',
    },
    {
      id: 'advanced_factory_machine',
      name: 'Advanced Factory Machine',
      inputs: new Map([['basic_factory_machine', 2], ['control_unit', 1], ['advanced_ic', 1]]),
      outputs: new Map([['advanced_factory_machine', 1]]),
      byproducts: new Map(),
      timeSeconds: 60,
      complexity: 9,
      tier: 5,
      energyCost: 800,
      heatGenerated: 0,
      category: 'manufacturing',
    },
    {
      id: 'basic_electronics',
      name: 'Basic Electronics',
      inputs: new Map([['integrated_circuit', 2], ['pcb', 1], ['plastic', 1]]),
      outputs: new Map([['basic_electronics', 1]]),
      byproducts: new Map(),
      timeSeconds: 30,
      complexity: 7,
      tier: 5,
      energyCost: 200,
      heatGenerated: 0,
      category: 'manufacturing',
    },
    {
      id: 'advanced_electronics',
      name: 'Advanced Electronics',
      inputs: new Map([['advanced_ic', 2], ['control_unit', 1], ['battery', 1]]),
      outputs: new Map([['advanced_electronics', 1]]),
      byproducts: new Map(),
      timeSeconds: 50,
      complexity: 9,
      tier: 5,
      energyCost: 400,
      heatGenerated: 0,
      category: 'manufacturing',
    },
    {
      id: 'food_ration',
      name: 'Food Ration',
      inputs: new Map([['purified_water', 2], ['wood', 3]]),
      outputs: new Map([['food_ration', 4]]),
      byproducts: new Map(),
      timeSeconds: 15,
      complexity: 5,
      tier: 5,
      energyCost: 30,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'medical_supply',
      name: 'Medical Supply',
      inputs: new Map([['chemical_resin', 1], ['purified_water', 1], ['plastic', 1]]),
      outputs: new Map([['medical_supply', 2]]),
      byproducts: new Map(),
      timeSeconds: 25,
      complexity: 7,
      tier: 5,
      energyCost: 80,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'comfort_item',
      name: 'Comfort Item',
      inputs: new Map([['lumber', 1], ['plastic', 1], ['copper_wire', 1]]),
      outputs: new Map([['comfort_item', 1]]),
      byproducts: new Map(),
      timeSeconds: 20,
      complexity: 6,
      tier: 5,
      energyCost: 50,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'building_block',
      name: 'Building Block',
      inputs: new Map([['brick', 2], ['cement', 1], ['steel_sheet', 1]]),
      outputs: new Map([['building_block', 3]]),
      byproducts: new Map(),
      timeSeconds: 20,
      complexity: 6,
      tier: 5,
      energyCost: 100,
      heatGenerated: 0,
      category: 'crafting',
    },
    {
      id: 'steel_frame',
      name: 'Steel Frame',
      inputs: new Map([['steel_sheet', 4], ['steel_pipe', 2]]),
      outputs: new Map([['steel_frame', 1]]),
      byproducts: new Map(),
      timeSeconds: 30,
      complexity: 7,
      tier: 5,
      energyCost: 200,
      heatGenerated: 0,
      category: 'assembly',
    },
    {
      id: 'basic_fuel_rod',
      name: 'Basic Fuel Rod',
      inputs: new Map([['steel', 3], ['uranium', 2], ['lead_ingot', 1]]),
      outputs: new Map([['basic_fuel_rod', 1]]),
      byproducts: new Map(),
      timeSeconds: 40,
      complexity: 8,
      tier: 5,
      energyCost: 300,
      heatGenerated: 500,
      category: 'manufacturing',
    },
  ];
}